[package]
name = "nice-grass"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "glam-pbr", "shader", "shared-structs"]

[dependencies]
anyhow = "1.0.45"
ash = "0.33.3"
ash-window = "0.7.0"
dolly = "0.1.4"
gltf = { version = "*", default-features = false, features = ["utils", "import", "KHR_materials_ior", "KHR_materials_transmission"] }
image = { version = "*", default-features = false }
gpu-allocator = "0.10.0"
ash-abstractions = { package = "ash-opinionated-abstractions", path = "../ash-opinionated-abstractions" }
winit = "0.25.0"
vk-sync = { package = "vk-sync-fork", version = "0.2.1" }
simplelog = "0.11.0"
log = "0.4.14"
shared-structs = { path = "shared-structs" }
glam = "0.19.0"
colstodian = { git = "https://github.com/termhn/colstodian" }

[profile.dev.package."*"]
opt-level = 3
