[package]
name = "nice-grass"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "glam-pbr", "shader", "shared-structs"]

[dependencies]
anyhow = "1.0.45"
ash = "0.33.3"
ash-window = "0.7.0"
dolly = { git = "https://github.com/expenses/dolly", branch = "bump-glam" }
gltf = { version = "0.16.0", default-features = false, features = ["utils"] }
gpu-allocator = "0.10.0"
image = { version = "0.23.14", features = ["png"], default-features = false }
ash-abstractions = { package = "ash-opinionated-abstractions", git = "https://github.com/expenses/ash-opinionated-abstractions" }
winit = "0.25.0"
vk-sync = { package = "vk-sync-fork", version = "0.2.1" }
simplelog = "0.11.0"
log = "0.4.14"
shared-structs = { path = "shared-structs" }
glam = "0.19.0"
