[package]
name = "thread-pool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.49"
num_cpus = "1.13.0"
parking_lot = "0.11.2"
